#Makefile generated by amake
#On Mon May  4 14:47:17 2020
#To print amake help use 'amake --help'.
CC=gcc
CPPC=g++
LINK=g++
SRCDIR=src
OBJDIR=obj
FLAGS=-g -Wall -std=c++11 -pthread 
LIBS=-lavcodec -lavformat -lavdevice -lavutil -lswscale -lX11 -lXcomposite -lGL 
OBJS=$(OBJDIR)/xcompgrab.o $(OBJDIR)/main.o $(OBJDIR)/writer.o 
EXEC=replayer
DATE=$(shell date +"%Y-%m-%d")

$(EXEC) : $(OBJS)
	$(LINK) $(OBJS) -o $(EXEC) $(FLAGS) $(LIBS)

$(OBJDIR)/xcompgrab.o: src/xcompgrab.c $(OBJDIR)/__setup_obj_dir
	$(CC) $(FLAGS) src/xcompgrab.c -c -o $@

$(OBJDIR)/main.o: src/main.cpp src/utils.h src/writer.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/main.cpp -c -o $@

$(OBJDIR)/writer.o: src/writer.cpp src/writer.h src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/writer.cpp -c -o $@

$(OBJDIR)/__setup_obj_dir :
	mkdir -p $(OBJDIR)
	touch $(OBJDIR)/__setup_obj_dir

.PHONY: clean bzip release

clean :
	rm -rf $(OBJDIR)/*.o
	rm -rf $(EXEC)

bzip :
	tar -cvf "$(DATE).$(EXEC).tar" $(SRCDIR)/* Makefile
	bzip2 "$(DATE).$(EXEC).tar"

release : FLAGS +=-O3 -D_RELEASE
release : $(EXEC)

